# This file was generated by GoReleaser. DO NOT EDIT.
class Tango < Formula
  desc "Tango is a command-line tool for dancing with access logs"
  homepage "https://github.com/roma-glushko/tango"
  version "1.0.3-rc1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/roma-glushko/tango/releases/download/1.0.3-rc1/tango_1.0.3-rc1_macOS_64-bit.zip"
    sha256 "5e7c1a9a60389699e75bed092e9ea4fd2efd3300185c03248b5c414d1ccb21c8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/roma-glushko/tango/releases/download/1.0.3-rc1/tango_1.0.3-rc1_Linux_64-bit.zip"
      sha256 "5741a92f436075fa06ede278899ea8531f98a3271f1160462a45a12e651c80cb"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/roma-glushko/tango/releases/download/1.0.3-rc1/tango_1.0.3-rc1_Linux_arm64.zip"
        sha256 "13cc8501dcb5678edd2d3fbe85c5316483639f0afe991f8d21fe667be19f0796"
      else
        url "https://github.com/roma-glushko/tango/releases/download/1.0.3-rc1/tango_1.0.3-rc1_Linux_armv6.zip"
        sha256 "65c8fb504a6c20ba0c4479f11401bb69f55e6e6aaafed214a8620c37def5e54a"
      end
    end
  end
  
  head "https://github.com/roma-glushko/tango.git"

  def install
    bin.install "tango"
  end

  def caveats; <<~EOS
    Tango is on the scene 🎉 Type `tango --help` to get started 💃💃💃
  EOS
  end

  test do
    system "#{bin}/tango --version"
  end
end
