# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tango < Formula
  desc "Tango is a command-line tool for dancing with access logs"
  homepage "https://github.com/roma-glushko/tango"
  version "1.2.0-rc4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roma-glushko/tango/releases/download/1.2.0-rc4/tango_1.2.0-rc4_macOS_64-bit.zip"
      sha256 "c107942a072088d6fd2a4fe06277c5355abff3c3103e9d88686fc5f1c8a37d52"

      def install
        bin.install "tango"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roma-glushko/tango/releases/download/1.2.0-rc4/tango_1.2.0-rc4_macOS_arm64.zip"
      sha256 "d2be5ea337d29b5067b21897717c6fdf35a5135b493b20844a73157af44c9d60"

      def install
        bin.install "tango"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/roma-glushko/tango/releases/download/1.2.0-rc4/tango_1.2.0-rc4_Linux_64-bit.zip"
      sha256 "a8d4dcc9b1edce0ae98a6427cf621d42495471724da816e378b2d30a4e421d9e"
      def install
        bin.install "tango"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roma-glushko/tango/releases/download/1.2.0-rc4/tango_1.2.0-rc4_Linux_arm64.zip"
      sha256 "68b5c8c8a43775808b1b2563853181bf1c5441015d019f4b97bfdab0b3071e7e"
      def install
        bin.install "tango"
      end
    end
  end

  def caveats
    <<~EOS
      Tango is on the scene! Type `tango --help` to get started
    EOS
  end

  test do
    system "#{bin}/tango --version"
  end
end
